name: CI

on:
  push:
    branches:
      - main  # Trigger on direct push to main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-15

    timeout-minutes: 8

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.2.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Install xcpretty
      run: gem install xcpretty

    - name: Build and Test
      run: |
        xcodebuild clean build test \
          -project EssentialFeed/EssentialFeed.xcodeproj \
          -scheme "CI" \
          -testPlan "CI" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGN_REQUIRED=NO \
          -sdk macosx \
          -destination "platform=macOS" \
          ONLY_ACTIVE_ARCH=YES \
          | xcpretty
