name: CI

# Controls when the action will run. 
# Triggers the workflow on push and pull request events, but only for the main branch.
on:
  push:
    branches:
      - main  # Trigger on direct push to main
  pull_request:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This workflow contains a single job called "build-and-test".
  build-and-test:
    # The type of runner that the job will run on.
    runs-on: macos-15

    timeout-minutes: 8

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
    - uses: actions/checkout@v4

    - name: Install xcpretty
      run: gem install xcpretty

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.2.0.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Build and Test
      run: |
        xcodebuild clean build test \
          -project EssentialFeed/EssentialFeed.xcodeproj \
          -scheme "CI" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
          -sdk macosx \
          -destination "platform=macOS" \
          ONLY_ACTIVE_ARCH=YES \
          | xcpretty
